# 基本設定
title: "KCRich566 website"
description: "This is my site."
baseurl: ""
url: "https://KCRich566.github.io"

# 作者資訊
author:
  name: "KCRich566"
  email: "KCRich566@gmail.com"

# GitHub Pages 設定
theme: "minima"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# 分頁配置
paginate: 5
paginate_path: "/page:num/"

# 自定義變數
nav:
    # 
  - name: "Home"
    link: "/"
    # 撰寫網頁說明
  - name: "About"
    link: "/about"
    # 撰寫我的內容
  - name: "Blog"
    link: "/blog"
    # 聯絡我
  - name: "Contact"
    link: "/contact"
    # 我的履歷
  - name: "Resume"
    link: "/resume"

# Markdown 處理器
markdown: kramdown
kramdown:
  input: "GFM"

# Sass 和 SCSS 選項
sass:
  style: compressed

# Exclusions
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor/

# Collections 設定
collections:
  my_collection:
    output: true
    permalink: /:collection/:path/

# 自定義變數 - 可用於模板和佈局中
custom_var: "Custom Value"

# 本地開發設定
future: true
show_drafts: false


